export enum EnumPropertyCategory {
  APARTMENT_SALE = 'APARTMENT_SALE',
  APARTMENT_RENT = 'APARTMENT_RENT',
  HOUSE_SALE = 'HOUSE_SALE',
  HOUSE_RENT = 'HOUSE_RENT',
  COMMERCIAL_SALE = 'COMMERCIAL_SALE',
  COMMERCIAL_RENT = 'COMMERCIAL_RENT',
  LAND_SALE = 'LAND_SALE',
  LAND_RENT = 'LAND_RENT',
}
