export type CategoryType =
  | "APARTMENT_SALE"
  | "APARTMENT_RENT"
  | "COMMERCIAL_SALE"
  | "COMMERCIAL_RENT"
  | "LAND_SALE"
  | "LAND_RENT"
  | "GARAGE_SALE"
  | "GARAGE_RENT"
  | "HOVLI_SALE"
  | "HOVLI_RENT";

export const categories: CategoryType[] = [
  "APARTMENT_SALE",
  "APARTMENT_RENT",
  "COMMERCIAL_SALE",
  "COMMERCIAL_RENT",
  "LAND_SALE",
  "LAND_RENT",
  "GARAGE_SALE",
  "GARAGE_RENT",
  "HOVLI_SALE",
  "HOVLI_RENT",
];

export const categorieType = {
  APARTMENT_SALE: "APARTMENT_SALE",
  APARTMENT_RENT: "APARTMENT_RENT",
  COMMERCIAL_SALE: "COMMERCIAL_SALE",
  COMMERCIAL_RENT: "COMMERCIAL_RENT",
  LAND_SALE: "LAND_SALE",
  LAND_RENT: "LAND_RENT",
  GARAGE_SALE: "GARAGE_SALE",
  GARAGE_RENT: "GARAGE_RENT",
  HOVLI_SALE: "HOVLI_SALE",
  HOVLI_RENT: "HOVLI_RENT",
};
