export type CategoryType =
  | "APARTMENT_SALE"
  | "APARTMENT_RENT"
  | "COMMERCIAL_SALE"
  | "COMMERCIAL_RENT";

export const categories: CategoryType[] = [
  "APARTMENT_SALE",
  "APARTMENT_RENT",
  "COMMERCIAL_SALE",
  "COMMERCIAL_RENT",
];

export const categorieType = {
  APARTMENT_SALE: "APARTMENT_SALE",
  APARTMENT_RENT: "APARTMENT_RENT",
  COMMERCIAL_SALE: "COMMERCIAL_SALE",
  COMMERCIAL_RENT: "COMMERCIAL_RENT",
};
